### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinacupac** [alptium/tamara.sevic#1]
Hi @Tamaralb  ,

Please do the following:

1. Write a comment below that you have received this test ticket. 
2. Please tag me using @ then typing my GitHub name.
3. Then close this ticket.

Thanks,
Valentina

**Comment by Tamaralb** [comment]
I received the test ticket. @valentinacupac

**Comment by Tamaralb** [comment]
@valentinacupac  I've done your task, you can review it.

**Comment by Tamaralb** [comment]
@valentinacupac  I have forgotten  to set the assignee as yourself, i made a correction.
