### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by Tamaralb** [alptium/tamara.sevic#3]

**Comment by Tamaralb** [comment]
@valentinacupac  I have done the task, you can review it now.

**Comment by valentinacupac** [comment]
@Tamaralb:
1. Class name should start with a capital letter.
2. Class name should be in English.
3. There should be a space before and after an operator. Example "int firstNumber= sc.nextInt();" --> this should be "int firstNumber = sc.nextInt();" and similarly "result=firstNumber + secondNumber;" should be "result = firstNumber + secondNumber;"
4. The brackets are not correctly aligned, see examples here https://docs.oracle.com/javase/tutorial/java/nutsandbolts/if.html the section "class IfElseDemo" and try to fix.

**Comment by Tamaralb** [comment]
@valentinacupac  You can review this task again.

**Comment by Tamaralb** [comment]
@valentinacupac You can review it now.

**Comment by valentinacupac** [comment]
@Tamaralb, correct.
